apiVersion: v1
kind: Secret
metadata:
  name: secret1
  namespace: spark
type: Opaque
stringData:
  hive-site.xml: |
    <configuration>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:mysql://mysql-service.data-services.svc.cluster.local:3306/metastore</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.mariadb.jdbc.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>cornel</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>purcel</value>
      </property>
    </configuration>
---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
  namespace: spark
type: Opaque
stringData:
  username: cornel
  password: purcel